#!/bin/bash 
  
#BSUB -P SYB112
#BSUB -W 2:00
#BSUB -J combine_tsvs
#BSUB -o ./logs/combine_tsvs_summit.%J.out
#BSUB -e ./logs/combine_tsvs_summit.%J.err
#BSUB -alloc_flags smt1
#BSUB -nnodes 233

source activate /gpfs/alpine2/syb112/proj-shared/Personal/jmerlet/envs/summit/mpi4py

py_script="/gpfs/alpine2/syb112/proj-shared/Projects/scrna-seq/code/comet/postprocess/combine_tsvs.py"
data_dir="/gpfs/alpine2/syb112/proj-shared/Projects/scrna-seq/data/human"

jsrun -n 233 -r 1 -a 1 -c 8 python $py_script -d $data_dir --run
