#!/bin/bash 
  
#BSUB -P SYB112
#BSUB -W 2:00
#BSUB -J comet_to_edge
#BSUB -o ./logs/comet_to_edge_summit.%J.out
#BSUB -e ./logs/comet_to_edge_summit.%J.err
#BSUB -alloc_flags smt1
#BSUB -nnodes 233

source activate /gpfs/alpine2/syb112/proj-shared/Personal/jmerlet/envs/summit/mpi4py

py_script="/gpfs/alpine2/syb112/proj-shared/Projects/scrna-seq/code/comet/postprocess/group_HHLL_jean.py"
data_dir="/gpfs/alpine2/syb112/proj-shared/Projects/scrna-seq/data/human"

jsrun -n 1864 -r 8 -c 5 -a 1  python $py_script -d $data_dir --run
